services:
  nextjs-static-export:
    build:
      context: .
      dockerfile: Dockerfile.export
    image: nextjs-static-export-image
    container_name: nextjs-static-export-container
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    restart: unless-stopped

  nextjs-static-export-with-serve:
    build:
      context: .
      dockerfile: Dockerfile.serve
    image: nextjs-static-export-serve-image
    container_name: nextjs-static-export-serve-container
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  nextjs-standalone-export:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    image: nextjs-standalone-image
    container_name: nextjs-standalone-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
